CREATE TABLE `leads` (
	`id` int AUTO_INCREMENT NOT NULL,
	`name` varchar(255) NOT NULL,
	`email` varchar(320) NOT NULL,
	`organization` varchar(255),
	`jobTitle` varchar(255),
	`phone` varchar(64),
	`country` varchar(100),
	`buyerType` enum('resort_hotel','distributor','importer','government','ngo','investment_firm','agricultural_business','other'),
	`formType` enum('trial_kit','technical_datasheet','export_desk','distributor','product_availability','company_profile','biochar_partnership','general_contact') NOT NULL,
	`productInterest` varchar(255),
	`incoterms` enum('fob','cif','ddp','tbd'),
	`destinationPort` varchar(255),
	`estimatedQuantity` varchar(255),
	`message` text,
	`status` enum('new','contacted','qualified','closed') NOT NULL DEFAULT 'new',
	`contentRequested` varchar(255),
	`contentDelivered` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `leads_id` PRIMARY KEY(`id`)
);
